server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: bubblemall
    url: jdbc:mysql://116.62.170.221:3306/bubblemall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: songhut
    password: Root123~

  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 50
        min-idle: 20